version: '3.4'

services:
  hackathon:
    image: ${DOCKER_REGISTRY-}hackathon
    build:
      context: .
      dockerfile: Hackathon/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Abcd1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver:/var/opt/mssql
    restart: always
    container_name: sqlserver

volumes:
  sqlserver:
