version: '3.8'

services:
  hackathon:
    image: ${DOCKER_REGISTRY-}hackathon
    build:
      context: .
      dockerfile: Hackathon.Api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver,1433;Initial Catalog=master;User ID=sa;Password=Abcd1234;TrustServerCertificate=True;
    volumes:
      - ./remote_debugger:/remote_debugger
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Abcd1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver:/var/opt/mssql
    restart: always
    container_name: sqlserver
    networks:
      - mynetwork

volumes:
  sqlserver:

networks:
  mynetwork:
    driver: bridge